services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn portfolio.wsgi:application"
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
