services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myportfolio.wsgi:application"
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
